//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DbContext", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Entity")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.ServiceReference1.SubwayContext))]
    public partial class DbContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubwayContext", Namespace="http://schemas.datacontract.org/2004/07/SubwayTest.Repository")]
    [System.SerializableAttribute()]
    public partial class SubwayContext : ConsoleApplication1.ServiceReference1.DbContext {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SubWayTest.Domain.SubWayMemberTicketInfo[] SubWayMemberTicketInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SubWayTest.Domain.SubWayTicket[] SubWayTicketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SubWayTest.Domain.SubwayMember[] SubwayMemberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SubWayTest.Domain.SubWayMemberTicketInfo[] SubWayMemberTicketInfo {
            get {
                return this.SubWayMemberTicketInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.SubWayMemberTicketInfoField, value) != true)) {
                    this.SubWayMemberTicketInfoField = value;
                    this.RaisePropertyChanged("SubWayMemberTicketInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SubWayTest.Domain.SubWayTicket[] SubWayTicket {
            get {
                return this.SubWayTicketField;
            }
            set {
                if ((object.ReferenceEquals(this.SubWayTicketField, value) != true)) {
                    this.SubWayTicketField = value;
                    this.RaisePropertyChanged("SubWayTicket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SubWayTest.Domain.SubwayMember[] SubwayMember {
            get {
                return this.SubwayMemberField;
            }
            set {
                if ((object.ReferenceEquals(this.SubwayMemberField, value) != true)) {
                    this.SubwayMemberField = value;
                    this.RaisePropertyChanged("SubwayMember");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISubwayMemberService")]
    public interface ISubwayMemberService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubwayMemberService/Index", ReplyAction="http://tempuri.org/ISubwayMemberService/IndexResponse")]
        void Index();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubwayMemberService/Index", ReplyAction="http://tempuri.org/ISubwayMemberService/IndexResponse")]
        System.Threading.Tasks.Task IndexAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubwayMemberService/Create", ReplyAction="http://tempuri.org/ISubwayMemberService/CreateResponse")]
        void Create(ConsoleApplication1.ServiceReference1.SubwayContext db, SubWayTest.Domain.SubwayMember subwayMember);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubwayMemberService/Create", ReplyAction="http://tempuri.org/ISubwayMemberService/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(ConsoleApplication1.ServiceReference1.SubwayContext db, SubWayTest.Domain.SubwayMember subwayMember);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubwayMemberService/Update", ReplyAction="http://tempuri.org/ISubwayMemberService/UpdateResponse")]
        void Update(SubWayTest.Domain.SubwayMember subwayMember);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubwayMemberService/Update", ReplyAction="http://tempuri.org/ISubwayMemberService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(SubWayTest.Domain.SubwayMember subwayMember);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubwayMemberService/Delete", ReplyAction="http://tempuri.org/ISubwayMemberService/DeleteResponse")]
        void Delete(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubwayMemberService/Delete", ReplyAction="http://tempuri.org/ISubwayMemberService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(System.Guid id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISubwayMemberServiceChannel : ConsoleApplication1.ServiceReference1.ISubwayMemberService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubwayMemberServiceClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference1.ISubwayMemberService>, ConsoleApplication1.ServiceReference1.ISubwayMemberService {
        
        public SubwayMemberServiceClient() {
        }
        
        public SubwayMemberServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubwayMemberServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubwayMemberServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubwayMemberServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Index() {
            base.Channel.Index();
        }
        
        public System.Threading.Tasks.Task IndexAsync() {
            return base.Channel.IndexAsync();
        }
        
        public void Create(ConsoleApplication1.ServiceReference1.SubwayContext db, SubWayTest.Domain.SubwayMember subwayMember) {
            base.Channel.Create(db, subwayMember);
        }
        
        public System.Threading.Tasks.Task CreateAsync(ConsoleApplication1.ServiceReference1.SubwayContext db, SubWayTest.Domain.SubwayMember subwayMember) {
            return base.Channel.CreateAsync(db, subwayMember);
        }
        
        public void Update(SubWayTest.Domain.SubwayMember subwayMember) {
            base.Channel.Update(subwayMember);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(SubWayTest.Domain.SubwayMember subwayMember) {
            return base.Channel.UpdateAsync(subwayMember);
        }
        
        public void Delete(System.Guid id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(System.Guid id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
