//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubWayTest.Test.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISubwayMemberService")]
    public interface ISubwayMemberService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubwayMemberService/Create", ReplyAction="http://tempuri.org/ISubwayMemberService/CreateResponse")]
        void Create(SubWayTest.Domain.SubwayMember member);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubwayMemberService/Create", ReplyAction="http://tempuri.org/ISubwayMemberService/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(SubWayTest.Domain.SubwayMember member);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISubwayMemberServiceChannel : SubWayTest.Test.ServiceReference1.ISubwayMemberService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubwayMemberServiceClient : System.ServiceModel.ClientBase<SubWayTest.Test.ServiceReference1.ISubwayMemberService>, SubWayTest.Test.ServiceReference1.ISubwayMemberService {
        
        public SubwayMemberServiceClient() {
        }
        
        public SubwayMemberServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubwayMemberServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubwayMemberServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubwayMemberServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Create(SubWayTest.Domain.SubwayMember member) {
            base.Channel.Create(member);
        }
        
        public System.Threading.Tasks.Task CreateAsync(SubWayTest.Domain.SubwayMember member) {
            return base.Channel.CreateAsync(member);
        }
    }
}
